### ISSUE TITLE
android7.0 状态栏半透遮罩

### ISSUE THREAD

**Issue by sweet2o09** [kyleduo/ExamplesFromMyBlog#1]
你好,我是在鸿洋的公众号里看到了你的这篇文章,之前我也有研究过沉浸式,最近遇到一个问题:

7.0以下的系统,我在style里面设置<item name="android:windowTranslucentStatus">true</item>的话,状态栏会是透明的.
但是在7.0的时候就会有个半透遮罩,不知道如何去掉,请问如何解决

**Comment by kyleduo** [comment]
你好，事实上android:windowTranslucentStatus这个属性为true的话，在5.0及以上，是表示状态栏半透明，而不是全透明。你说的7.0系统的半透明遮罩是正常的。你测试用的7.0以下的系统，是什么设备？

**Comment by sweet2o09** [comment]
我测试过7.0以下小米,华为手机,都是全透效果,然后7.0的华为手机上看就是半透

**Comment by kyleduo** [comment]
嗯，国内的ROM可能会修改默认的特性。建议开发的时候也在模拟器原生系统跑一下。
