### ISSUE TITLE
Fragment中使用半透明状态栏异常

### ISSUE THREAD

**Issue by stridercheng** [kyleduo/ExamplesFromMyBlog#2]
常规的布局，在LinearLayout上设置fitSystemWindows="true"属性。当在Activity中布局时，跟你的SecondActivity是一样的，显示正常。然后把布局拿放到Fragment中，Activity中使用FragmentManager注入这个Fragment后，无论怎么设置fitSystemWindows属性，都无法正常显示。

**Comment by kyleduo** [comment]
不管是Fragment还是Activity，都是要保证你期望的那个View的所有父节点的fitsSystemWindows属性为false，否则就会被提前消费。
如果是在Fragment中使用这个属性，同时也要检查Activity的布局是否也用了这个属性。
Demo里新增了Fragment的场景。

**Comment by stridercheng** [comment]
好的，谢谢。

**Comment by kyleduo** [comment]
我又添加了一个Demo，LinearLayout没有问题，你看下你那边是什么原因吧。
另外Toolbar如果不调用setSupportActionBar(toolbar);，你看到的显示异常并不是fitsSystemWindows没有生效，而是Measure过程没有符合预期，猜测应该是设置的theme没有生效导致的，没有深入研究。

**Comment by stridercheng** [comment]
非常感谢你的耐心答复。我更新最新的代码看了，LinearLayout其实是存在问题的，有一部分与startusbar重合了，正常的显示应该应该是在statusbar下面吧。我的系统是android 7.1 
![screenshot_20170517-114459](https://cloud.githubusercontent.com/assets/8637437/26137679/5a27596a-3af6-11e7-847c-0fbfd83431ce.png)
![screenshot_20170517-114504](https://cloud.githubusercontent.com/assets/8637437/26137680/5a37e15e-3af6-11e7-8a0f-c64706e5e938.png)

**Comment by kyleduo** [comment]
你还是没有理解fitsSystemWindows的作用，我博客中有写：

> fitsSystemWindows属性表明该View将根据Window的Insets进行适应，这个“适应”，一般来说是设置padding，CollapsingToolbarLayout的处理方法是对子View进行offset偏移。共同点是：表明该View的内容或者子View要向下移出状态栏的区域。一般情况下，只需要给一个View设置该属性。

注意是 **内容** 向下移出状态栏的区域，并不是这个View自身向下移出状态栏区域。如果你需要LinearLayout移出区域，你需要给LinearLayout的父控件设置fitsSystemWindows属性。

**Comment by stridercheng** [comment]
我又看了一遍你的博客，确实是这样的。请问如果用linearlayout如何在fragment里边实现透明状态栏呢。设置给父控件的话，linearlayout确实往下移了，但是状态栏变成了灰色的，这种情况应该怎么办？
![screenshot_20170517-132516_01](https://cloud.githubusercontent.com/assets/8637437/26139581/551b2d08-3b04-11e7-985f-47725761432f.png)

**Comment by kyleduo** [comment]
这就看你需求了呀，要是你希望状态栏下面有颜色，就在现在的LinearLayout外层再套一层就行了。
